name: docker CI

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.image.image_name }}:${{ matrix.image.image_tag }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - { image_name: bensuperpc/dev-environment, image_tag: debian-latest }
          - { image_name: bensuperpc/dev-environment, image_tag: alpine-latest }
          - { image_name: bensuperpc/dev-environment, image_tag: ubuntu-latest }
          - {
              image_name: bensuperpc/dev-environment,
              image_tag: archlinux-latest,
            }
          - { image_name: bensuperpc/dev-environment, image_tag: fedora-latest }
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: "Pull docker image"
        run: docker pull ${{ matrix.image.image_name }}:${{ matrix.image.image_tag }}

      - name: "make base"
        run: docker run --rm -v "$PWD":/usr/src/myapp --workdir /usr/src/myapp ${{ matrix.image.image_name }}:${{ matrix.image.image_tag }} make base

      - name: "make release"
        run: docker run --rm -v "$PWD":/usr/src/myapp --workdir /usr/src/myapp ${{ matrix.image.image_name }}:${{ matrix.image.image_tag }} make release

      - name: "make debug"
        run: docker run --rm -v "$PWD":/usr/src/myapp --workdir /usr/src/myapp ${{ matrix.image.image_name }}:${{ matrix.image.image_tag }} make debug
